# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  encoding: utf8
  database: gestion_development
  username: maxenz
  password: elmaxo
  host: 127.0.0.1
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  database: gestion
  username: maxenz
  password: elmaxo
  host: 192.168.0.248
  port: 3306
